name: Sync Code Changes to OrgNotIncluded
on:
  push:
    branches:
      - 'main'
jobs:
  sync:
    if: github.repository == 'org-not-included/ds-tour'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Pushes to another repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
      with:
        source-directory: .
        destination-github-username: 'siddarthpatel'
        destination-repository-name: 'ds-tour'
        user-name: orgnotincluded
        user-email: orgnotincluded@gmail.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: main
