name: Sync Code Changes to OrgNotIncluded
on:
  push:
    branches:
      - 'main'
jobs:
  sync:
    env:
      GITHUB_PAT: ${{secrets.DS_TOUR_PAT}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Sync Updates to ds-tour repo in OrgNotIncluded
      shell: bash
      run: |
        echo -e "Current Directory: $(pwd)"
        git remote rename origin upstream
        git remote add origin https://siddarthpatel:${GITHUB_PAT}@github.com/org-not-included/ds-tour
        git push -f origin main
